### ISSUE TITLE
CONTEXT (0xA3) and ADD_CONTEXT (0xA9)

### ISSUE THREAD

**Issue by sbobykin** [Grandison-RG/mpemu#7]
### In
`[<len. of the service name including "\0">, 0xA3, <service name>]`
for example: `[12, 0xA3, "example.com"]`

### Out 
`[1, <result byte>]` where `result = 0x00` when there is no `<service name>`, `result = 0x01` when so.

Actually using this (`CONTEXT`) command we check: do we have `service` name in the device storage or not?

### In
`[<len of service name to add including "\0">, 0xA9, <service name>]`
### Out
`[1, <result byte>]` where `result = 0x00` when we have failed to add a new service name, `result = 0x01` when so. 

Using `ADD_CONTEXT` we add a new service name to the device storage.

## Memory model for the task
```
struct State {
  ListofParentNodes: List<ParentNode>
  ArrayOfNodes: Array<Node>
}

struct ParentNode: Node {
  service: String //for ex.: "example.com"
}

struct Node {
  nodeIndex: Uint // index of node (parent, child ...) in the ArrayOfNodes
}
```
## Implementation notes
When we add a new parent node we append it into the both structures: `ListOfParentNodes` and `ArrayOfNodes`.

For the `ListOfParentNodes` we must do this addition in alphabetical order according to the `service` name.

As for `ArrayOfNodes` we need to tell the following. This array can contain some `node` or `nothing`. For example, `[node1, node2, nothing, node3, nothing, nothing, node4]`. We add a new parent node replacing nothing. Or if there is not free `nothing` then we add it into the end of `ArrayOfNodes`.

**Comment by etodemerzel** [comment]
data ChildeNode = ChildeNode String String Word8

data ParentNode = ParentNode String  [ChildeNode]

**Comment by sbobykin** [comment]
A kind of parent and child node defs. in Haskell.
```
type NodeIndex = Word

data Node = ParentNode | ChildNode

data ParentNode = ParentNode String [ChildNode] NodeIndex
data ChildNode =  ChildNode String String NodeIndex
```
