### ISSUE TITLE
SET_LOGIN, ListOfChildNodes and CONTEXT extenstion

### ISSUE THREAD

**Issue by sbobykin** [Grandison-RG/mpemu#9]
## CONTEXT (0xA3)
We need to store current `context` into the memory. If we have a `service` in the list of parent nodes then we set current `context` to this `service`,

## SET_LOGIN (0xA6)
Here we set login for the current context (by context we can find parent node). if login exists then we do nothing if doesn't exists then we create new child node. In both cases we return success value (0x01).

### In
`[<len. of the login name including "\0">, 0xA6, <login name>]`
for example: `[4, 0xA6, "bob"]`

### Out 
`[1, 0xA6, 0x01]`

## Storage
```
data Storage = Storage
  {
    listOfParentNodes :: [ParentNode]
    lastIndex  :: Int
    context :: String
  }

data ParentNode = ParentNode
  {
    listOfChildNodes :: [ChildNode]
    service :: String
    nodeIndex :: Int
  }

data ChildNode = ChildNode
  {
    login :: String
    nodeIndex :: Int
  }
```

**Comment by Elvecent** [comment]
>for example: [12, 0xA3, "bob"]

wut

Each child node has its own login. Which exactly is supposed to be modified by SET_LOGIN?

**Comment by sbobykin** [comment]
@Elvecent I've updated ticket description to answer your questions.

**Comment by Elvecent** [comment]
@sbobykin Thanks!
